# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomment.proto\x12\x0e\x63ommentservice\"C\n\x0e\x43ommentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"X\n\x0f\x43ommentResponse\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07post_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t2b\n\x0e\x43ommentService\x12P\n\rCreateComment\x12\x1e.commentservice.CommentRequest\x1a\x1f.commentservice.CommentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMMENTREQUEST']._serialized_start=33
  _globals['_COMMENTREQUEST']._serialized_end=100
  _globals['_COMMENTRESPONSE']._serialized_start=102
  _globals['_COMMENTRESPONSE']._serialized_end=190
  _globals['_COMMENTSERVICE']._serialized_start=192
  _globals['_COMMENTSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
