# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x0bpostservice\"/\n\x0bPostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"A\n\x0cPostResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t2P\n\x0bPostService\x12\x41\n\nCreatePost\x12\x18.postservice.PostRequest\x1a\x19.postservice.PostResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POSTREQUEST']._serialized_start=27
  _globals['_POSTREQUEST']._serialized_end=74
  _globals['_POSTRESPONSE']._serialized_start=76
  _globals['_POSTRESPONSE']._serialized_end=141
  _globals['_POSTSERVICE']._serialized_start=143
  _globals['_POSTSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
